# main settings
title: Raising the Volume!
description: Amplifying <i>Soul of Reason</i>
email: soulofreason [at] nyu [dot] edu
repository: nyu-dss/soul-of-reason
url: ''
baseurl: '/soul-of-reason'

# build settings
permalink: pretty
incremental: true
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
  - kramdown
  - rouge
collections:
  pages:
    output: true

# theme settings
remote_theme: chrisrhymes/bulma-clean-theme
favicon: 'assets/favicon.png'
