# site settings
title: Raising the Volume!
description: Amplifying <i>Soul of Reason</i>
email: soulofreason [at] nyu [dot] edu
repository: nyu-dss/soul-of-reason

# build settings
theme: bulma-clean-theme
favicon: 'assets/favicon.png'
permalink: pretty

collections:
  pages:
    output: true
