---
title: Raising the Volume!
timezone: UTC
collections:
  pages:
    title: Pages
    output: true
  posts:
    title: Posts
    output: true
  updates:
    title: Updates
    output: true
    permalink: updates/:title/
  uploads:
    title: Uploads
    output: true
subtitle: Amplifying <i>Soul of Reason</i>
email: soulofreason [at] nyu [dot] edu
repository: nyu-dss/soul-of-reason
url: ''
baseurl: "/soul-of-reason"
permalink: pretty
markdown: kramdown
incremental: true
plugins:
- jekyll-sitemap
- jekyll-redirect-from
- jekyll-paginate
- jekyll-feed
- jekyll-remote-theme
- jekyll-seo-tag
- kramdown
- rouge
whitelist:
- jekyll-redirect-from
remote_theme: chrisrhymes/bulma-clean-theme
favicon: assets/favicon.png
