# netlify config
backend:
  name: git-gateway
  branch: main
media_folder: 'images/uploads'
collections:
  - name: posts
    label: posts
    folder: _posts
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
