# netlify config
backend:
  name: github
  repo: nyu-dss/soul-of-reason
media_folder: 'images/uploads'
collections:
  - name: posts
    label: posts
    folder: _posts
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
